app_name: ドキュメント自動要約&作成アプリ
version: 1.0.0
language: ja
theme: default
window:
  width: 1200
  height: 800
  resizable: true
logging:
  level: INFO
  max_size: 10MB
  backup_count: 5
template_selection:
  last_selected: weekly_report
  config:
    output_format: txt
    summary_level: 3
    max_chars: 2000
    extract_keywords: true
    include_stats: true
    use_llm: false
